In [4]:
import pandas as pd
import gzip
import pickle

In [14]:
with gzip.open(r"D:\Desktop\BasicProject\任从辉\pkl数据集\ideastoimpacts\002\lidar\00.pkl.gz", 'r') as f:
    data = pickle.load(f)

In [15]:
data

x           y         z     i             t  d
index                                                          
0       -75.131138  -79.331690  3.511804   7.0  1.557540e+09  0
1      -112.588306 -118.666002  1.423499  31.0  1.557540e+09  0
2       -42.085902  -44.384891  0.593491   7.0  1.557540e+09  0
3       -27.329435  -28.795053 -0.403781   0.0  1.557540e+09  0
4        -6.196208   -6.621082  1.130009   3.0  1.557540e+09  0
...            ...         ...       ...   ...           ... ..
166763   27.670526   17.159726  3.778677  25.0  1.557540e+09  1
166764   27.703935   17.114063  3.780626  27.0  1.557540e+09  1
166765   27.560664   16.955518  3.767948  18.0  1.557540e+09  1
166766   27.384433   16.783824  3.752670  22.0  1.557540e+09  1
166767   27.228821   16.626038  3.739154  20.0  1.557540e+09  1

[166768 rows x 6 columns]

In [16]:
type(data)

pandas.core.frame.DataFrame

In [19]:
data['x'].values

array([ -75.13113788, -112.58830608,  -42.08590168, ...,   27.56066404,
         27.38443338,   27.22882095])

In [23]:
data.values

array([[-7.51311379e+01, -7.93316897e+01,  3.51180427e+00,
         7.00000000e+00,  1.55753996e+09,  0.00000000e+00],
       [-1.12588306e+02, -1.18666002e+02,  1.42349938e+00,
         3.10000000e+01,  1.55753996e+09,  0.00000000e+00],
       [-4.20859017e+01, -4.43848908e+01,  5.93490847e-01,
         7.00000000e+00,  1.55753996e+09,  0.00000000e+00],
       ...,
       [ 2.75606640e+01,  1.69555183e+01,  3.76794770e+00,
         1.80000000e+01,  1.55753996e+09,  1.00000000e+00],
       [ 2.73844334e+01,  1.67838237e+01,  3.75266969e+00,
         2.20000000e+01,  1.55753996e+09,  1.00000000e+00],
       [ 2.72288210e+01,  1.66260378e+01,  3.73915448e+00,
         2.00000000e+01,  1.55753996e+09,  1.00000000e+00]])

In [7]:
with gzip.open(r"D:\Desktop\BasicProject\任从辉\pkl数据集\ideastoimpacts\002\annotations\cuboids\00.pkl.gz", 'r') as f:
    data1 = pickle.load(f)

In [8]:
data1

uuid                   label       yaw  \
0    e83d78e4-5b11-4ad5-ac71-917b5cd19c94                     Car -0.840044   
1    b113987c-bde4-43b3-b7f2-8a9a80318ae2                     Car  2.352911   
2    47a397d6-9f2f-4e3b-9316-00ad60320f6d                     Car  2.387817   
3    92b61b3d-8f2f-4205-921b-fdc047ab86e2                     Car -0.787685   
4    895e6a77-1506-4f55-a977-baf5f86840e1                     Car  2.405271   
..                                    ...                     ...       ...   
108  7e583638-55ad-4a89-ac84-bd0a2554ebfe  Pedestrian with Object  0.873127   
109  5d2db8b6-13e5-4c8f-9c10-c64a817d8db7                     Car  2.386263   
110  ad246d6d-9935-46ae-9639-e1a809f38dee  Pedestrian with Object -2.254502   
111  47128e0a-f30a-46d7-bf22-db63d5eb724a              Pedestrian  2.316954   
112  cdc9ec76-991f-4c96-a05e-01b92bf0f485              Pedestrian -0.742749   

     stationary  camera_used  position.x  position.y  position.z  \
0          True            2       7.361       2.630       0.487   
1          True            5     -12.659       6.353       0.361   
2          True            4     -41.504     -22.578       0.393   
3          True            1      11.697       7.260       0.548   
4          True            4     -51.568     -32.920       0.486   
..          ...          ...         ...         ...         ...   
108       False           -1      43.144      74.100       0.534   
109       False            1      61.197      80.254       0.242   
110       False            1      47.513      71.603       0.534   
111       False            1      84.584     109.437       0.683   
112       False            1      40.439      32.311       0.585   

     dimensions.x  dimensions.y  dimensions.z attributes.object_motion  \
0           1.888         4.747         1.761                   Parked   
1           1.837         4.269         1.523                   Parked   
2           1.930         4.358         1.623                   Parked   
3           2.099         5.170         1.821                   Parked   
4           1.967         4.608         1.710                   Parked   
..            ...           ...           ...                      ...   
108         0.613         0.748         1.811                      NaN   
109         1.959         4.327         1.928                   Moving   
110         0.613         0.810         1.811                      NaN   
111         0.638         0.580         1.766                      NaN   
112         0.855         0.724         1.820                      NaN   

                       cuboids.sibling_id  cuboids.sensor_id  \
0                                       -                 -1   
1                                       -                 -1   
2                                       -                 -1   
3                                       -                 -1   
4                                       -                 -1   
..                                    ...                ...   
108  b588c721-4627-4703-b8ce-29b029ed75f0                  1   
109  fb2902a3-e965-47b6-bf18-b0d519ef34e5                  1   
110  2b5714a8-e181-41f8-99ad-6f0adfae7e47                  1   
111  57b0c4f7-d36e-4d7a-af85-fb7de8f139c0                  1   
112  d08ed3ec-40de-4c70-a34d-e83d59f38883                  1   

    attributes.rider_status attributes.pedestrian_behavior  \
0                       NaN                            NaN   
1                       NaN                            NaN   
2                       NaN                            NaN   
3                       NaN                            NaN   
4                       NaN                            NaN   
..                      ...                            ...   
108                     NaN                        Walking   
109                     NaN                            NaN   
110                     NaN                        Walk

In [9]:
type(data1)

pandas.core.frame.DataFrame

In [24]:
with gzip.open(r"D:\Desktop\BasicProject\任从辉\pkl数据集\ideastoimpacts\002\annotations\cuboids\01.pkl.gz", 'r') as f:
    data3 = pickle.load(f)

In [34]:
type(data3.uuid)

pandas.core.series.Series

In [32]:
for k in data1.uuid:
    if k in data3.uuid:
        continue
    else:
        print(k)

e83d78e4-5b11-4ad5-ac71-917b5cd19c94
b113987c-bde4-43b3-b7f2-8a9a80318ae2
47a397d6-9f2f-4e3b-9316-00ad60320f6d
92b61b3d-8f2f-4205-921b-fdc047ab86e2
895e6a77-1506-4f55-a977-baf5f86840e1
cb51296e-bf80-4907-bedc-02a8188f6e44
0f07d022-eb73-44bf-a125-7f4fb849647d
5d7cce90-c6be-4b8e-b9bc-c775b7e513e9
7e9ec7d7-de00-4fcf-8d12-9723d1f55b6b
adf0a251-a26f-45df-a216-980875893b88
63e2de09-ba4a-4c71-b6d6-05275b3f6907
81876c58-784c-4244-ba69-d8d3e7824c9a
b769a1fd-b6ba-4b58-998a-b814e23baa30
576b524d-c126-49c6-99a7-230475c4c05a
9a54d0a1-0aad-440a-8a51-62db061aa64c
e03a4c57-b98c-4bde-a887-be5c8669380f
bdc0f646-0d15-408a-8fcf-274688625e7a
0f39c013-155d-493c-8971-479f2b585662
c1ac7b66-dca7-434a-b3d4-965991c54d2c
6e11028a-f0e6-43e9-994d-bef1dcf4de37
f382dfe9-7902-406e-8aec-3d250c0e51ec
082cccd6-8637-4033-b12a-05d5ff30f22d
25af0d2b-a032-40df-b434-aeff66633850
418b7f15-e6c4-40fe-b440-ff747b22430b
49914840-b88c-4c45-9c07-d3271197b566
0e0186d7-d2cd-468b-b786-8f7058c95643
fa77ad4e-f5dd-4be9-8071-2b35fd24af38
9

In [30]:
len(data1)

113

In [31]:
len(data3)

114

In [15]:
data1.iloc[1]['yaw']

2.3529106532030197

In [10]:
len(data1)

113

In [5]:
with gzip.open(r"D:\Desktop\BasicProject\任从辉\pkl数据集\ideastoimpacts\002\annotations\semseg\00.pkl.gz", 'r') as f:
    data2 = pickle.load(f)

In [9]:
data2

KeyError: 1667689

In [12]:
l = data2['class'].values
l = l.tolist()
l[166760]

5

In [8]:
len(l)

166768

In [17]:
from scipy.spatial.transform import Rotation as R
import numpy as np
import json

In [ ]:
r = R.from_quat([0.0044630298247378356, 0.017858463809403605, 0.38486839890864721, 0.92278788036939774]).as_matrix()
r

In [45]:
t = [1, 2, 3]
t = np.asarray(t).reshape((3, 1))

In [46]:
a = np.hstack((r, t))
a

array([[ 0.70311478, -0.71014438,  0.03639451,  1.        ],
       [ 0.71046319,  0.70371279,  0.00550946,  2.        ],
       [-0.02952379,  0.02198318,  0.99932231,  3.        ]])

In [48]:
def load_json(json_path:str):
    with open(json_path, 'r', encoding='utf-8') as f:
        content = f.read()
        json_content = json.loads(content)
    return json_content

In [49]:
d = load_json(r"D:\Desktop\BasicProject\任从辉\pkl数据集\ideastoimpacts\002\camera\left_camera\poses.json")

In [54]:
np.asarray(list(d[0]['position'].values())).reshape((3,1))

array([[0.05624796],
       [0.72713553],
       [1.59268427]])

In [3]:
import os

In [6]:
def load_pkl(pkl_file):
    with gzip.open(pkl_file, 'r') as f:
        data = pickle.load(f)
        points_array = data.values
    return points_array

SyntaxError: unmatched ')' (627105423.py, line 2)

In [18]:
np.array([0, 1, 2]).reshape((3,1))

array([[0],
       [1],
       [2]])