In [18]:
import math
x = -1
y = 0
z = 1

pi = math.pi
b_alpha = 0
theta = math.atan2(x, z)
theta

-0.7853981633974483

In [19]:
r_y = -1 * (b_alpha + (math.pi / 2))
r_y

-1.5707963267948966

In [14]:
alpha = "%.2f" % float(r_y - theta)
alpha

'0.00'

In [13]:
from scipy.spatial.transform import Rotation as R
from numpy.linalg import inv
import numpy as np
r = R.from_euler('xyz', [x, y, z]).as_matrix()
r

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
r @ a

array([1., 1., 1.])

In [10]:
b = [-1, 1, -1]
inv(r) @ b

array([1., 1., 1.])

In [12]:
import json
with open(r"D:\Desktop\empty2.json", 'r', encoding='utf-8') as f:
    content = f.read()
    json_content = json.loads(content)

In [13]:
json_content

''

In [14]:
if json_content == None:
    print(1)
else:
    print

In [9]:
a = ''

In [11]:
with open(r"D:\Desktop\empty2.json", 'w', encoding='utf-8') as ef:
    ef.write(json.dumps(a))

In [15]:
import numpy as np

In [18]:
p = np.array([283.914917, 0, 335.8605074, 0, 0, 288.4213562, 238.035394, 0, 0, 0, 1, 0]).reshape(3, 4)
p

array([[283.914917 ,   0.       , 335.8605074,   0.       ],
       [  0.       , 288.4213562, 238.035394 ,   0.       ],
       [  0.       ,   0.       ,   1.       ,   0.       ]])

In [19]:
r = np.array([1,	0,	0,	0,	1,	0,	0,	0,	1]).reshape(3,3)
r

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
k = np.array([292.1274058,	0,	335.0661855,	0,	292.1628842,	238.4474201,	0,	0,	1]).reshape(3, 3)
k

array([[292.1274058,   0.       , 335.0661855],
       [  0.       , 292.1628842, 238.4474201],
       [  0.       ,   0.       ,   1.       ]])