In [18]:
from load_pcd_points import load_pc_data
import numpy as np

In [2]:
file = r"D:\Data\we_chat_files\WeChat Files\wxid_pzn3n31pjyvc29\FileStorage\File\2023-01\2022-11-19_08-17-14_517_8_seg_0_clip_0_sample_sensor_aligned\2022-11-19_08-17-14_517_8_seg_0_clip_0_sample_sensor_aligned\lidar_top\1668819435.023404906.pcd"
points = load_pc_data(file)

In [7]:
points

array([[ 2.3150009e+01,  4.1407585e+01, -7.4638133e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.0744657e+02,  1.8478523e+02, -2.5696869e+01, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 9.9826403e+00,  1.5793435e+01, -3.4578760e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [ 1.8485144e+00, -2.6480486e+00, -7.0250779e-02, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.7984883e+00, -2.5908897e+00, -9.6031040e-02, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.7859169e+00, -2.5876997e+00, -9.5723420e-02, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [30]:
b = int((255<<16)+(0<<8)+0)
b

16711680

In [10]:
xyz = points[:, 0:3]
xyz

array([[ 2.3150009e+01,  4.1407585e+01, -7.4638133e+00],
       [ 1.0744657e+02,  1.8478523e+02, -2.5696869e+01],
       [ 9.9826403e+00,  1.5793435e+01, -3.4578760e+00],
       ...,
       [ 1.8485144e+00, -2.6480486e+00, -7.0250779e-02],
       [ 1.7984883e+00, -2.5908897e+00, -9.6031040e-02],
       [ 1.7859169e+00, -2.5876997e+00, -9.5723420e-02]], dtype=float32)

In [12]:
channel = points[:, 8:9]
channel

array([[43.],
       [39.],
       [46.],
       ...,
       [75.],
       [76.],
       [76.]], dtype=float32)

In [31]:
rgb = []
for c in channel:
    if 1<=c<=16 or 65<=c<=80:
        rgb.append(16711680)
    else:
        rgb.append(65280)
rgb

[65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,
 65280,


In [17]:
rgb.count(65280)

19104

In [32]:
points = np.hstack((xyz, np.array(rgb, dtype=np.uint32).reshape((-1, 1))))
points

array([[ 2.31500092e+01,  4.14075851e+01, -7.46381330e+00,
         6.52800000e+04],
       [ 1.07446571e+02,  1.84785233e+02, -2.56968689e+01,
         6.52800000e+04],
       [ 9.98264027e+00,  1.57934351e+01, -3.45787597e+00,
         6.52800000e+04],
       ...,
       [ 1.84851444e+00, -2.64804864e+00, -7.02507794e-02,
         1.67116800e+07],
       [ 1.79848826e+00, -2.59088969e+00, -9.60310400e-02,
         1.67116800e+07],
       [ 1.78591692e+00, -2.58769965e+00, -9.57234204e-02,
         1.67116800e+07]])

In [33]:
with open(rf"D:\Data\we_chat_files\WeChat Files\wxid_pzn3n31pjyvc29\FileStorage\File\2023-01\2022-11-19_08-17-14_517_8_seg_0_clip_0_sample_sensor_aligned\2022-11-19_08-17-14_517_8_seg_0_clip_0_sample_sensor_aligned\test.pcd", 'w', encoding='ascii') as pcd_file:
        point_num = points.shape[0]
        heads = [
            '# .PCD v0.7 - Point Cloud Data file format',
            'VERSION 0.7',
            'FIELDS x y z rgb',
            'SIZE 4 4 4 4',
            'TYPE F F F U',
            'COUNT 1 1 1 1',
            f'WIDTH {point_num}',
            'HEIGHT 1',
            'VIEWPOINT 0 0 0 1 0 0 0',
            f'POINTS {point_num}',
            'DATA ascii'
        ]
        pcd_file.write('\n'.join(heads))
        for i in range(point_num):
            string_point = '\n' + str(points[i, 0]) + ' ' + str(points[i, 1]) + ' ' + str(points[i, 2]) + ' ' + str(points[i, 3])
            pcd_file.write(string_point)

In [37]:
1950/7

278.57142857142856

In [43]:
7000-6746

254

In [44]:
5852-254

5598