In [11]:
import matplotlib.pyplot as plt
from nptdms import TdmsFile
import numpy as np
import pandas as pd

In [20]:
with TdmsFile.open(r'D:\Desktop\BasicProject\my_file.tdms') as tdms_file:
    for group in tdms_file.groups():      # TdmsFile可以按组名索引来访问TDMS文件中的组，使用groups()方法直接访问所有组
        group_name = group.name
        print(group_name)
    for channel in group.channels():      # TdmsGroup 可以通过通道名称来索引来访问这个组中的一个通道，使用 channels()方法直接访问所有通道
        channel_name = channel.name
        print(channel_name)
    channel = tdms_file['group_1']['channel_1']  # 根据索引读取通道
    all_channel_data = channel[:]                  # 将此通道中所有的数据作为numpy数组获取
    num = np.array(all_channel_data)
    print(num)



group_1
channel_1
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [21]:
tdms_file = TdmsFile.read(r"C:\Users\EDY\Downloads\exampleMeasurements.tdms")

In [27]:
type(tdms_file)

nptdms.tdms.TdmsFile

In [31]:
all_groups = tdms_file.groups()
for group in all_groups:
    print(group.name)
print(all_groups)

EHM
[<TdmsGroup with path /'EHM'>]


In [32]:
all_group_channels = group.channels()
for channel in all_group_channels:
    print(channel)

<TdmsChannel with path /'EHM'/'VaGroundV'>
<TdmsChannel with path /'EHM'/'VbGroundV'>
<TdmsChannel with path /'EHM'/'VcGroundV'>
<TdmsChannel with path /'EHM'/'VaVbV'>
<TdmsChannel with path /'EHM'/'VbVcV'>
<TdmsChannel with path /'EHM'/'VcVaV'>
<TdmsChannel with path /'EHM'/'CurrentA'>
<TdmsChannel with path /'EHM'/'CurrentB'>
<TdmsChannel with path /'EHM'/'CurrentC'>
<TdmsChannel with path /'EHM'/'SensoPowerV'>
<TdmsChannel with path /'EHM'/'TorqueNm'>
<TdmsChannel with path /'EHM'/'LoadN'>
<TdmsChannel with path /'EHM'/'TemperatureC'>
<TdmsChannel with path /'EHM'/'HallSensor'>
<TdmsChannel with path /'EHM'/'SoundPressurePa'>
<TdmsChannel with path /'EHM'/'AccelX'>
<TdmsChannel with path /'EHM'/'AccelY'>
<TdmsChannel with path /'EHM'/'AccelZ'>


In [33]:
all_data = tdms_file['EHM']['AccelX'][:]
all_data

array([ 0.00433087, -0.00256777, -0.00536799, ..., -0.00800729,
        0.00939131,  0.01466393])

In [35]:
all_data2 = tdms_file['EHM']['AccelY'][:]
all_data2

array([ 0.00436544, -0.01236439, -0.017277  , ..., -0.00970602,
        0.00852346,  0.01237035])

In [17]:
channel = tdms_file[group_name][channel_name]  # 根据索引读取通道
all_channel_data = channel[:]                  # 将此通道中所有的数据作为numpy数组获取
num = np.array(all_channel_data)
num                              # 维度查看


RuntimeError: Cannot read data after the underlying TDMS reader is closed

In [13]:
from nptdms import TdmsWriter, RootObject, GroupObject, ChannelObject

root_object = RootObject(properties={
    "prop1": "foo",
    "prop2": 3,
})
group_object = GroupObject("group_1", properties={
    "prop1": 1.2345,
    "prop2": False,
})
data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
channel_object = ChannelObject("group_1", "channel_1", data, properties={})

with TdmsWriter(r"D:\Desktop\BasicProject\my_file.tdms") as tdms_writer:
    # Write first segment
    tdms_writer.write_segment([
        root_object,
        group_object,
        channel_object])
    # Write another segment with more data for the same channel
    more_data = np.array([6.0, 7.0, 8.0, 9.0, 10.0])
    channel_object = ChannelObject("group_1", "channel_1", more_data, properties={})
    tdms_writer.write_segment([channel_object])

In [1]:
import math

In [3]:
x = 0
y = 1
math.atan2(y, x)

1.5707963267948966