In [2]:
# _*_ coding=: utf-8 _*_
import laspy
import numpy as np

las=laspy.read(r"D:\Desktop\sx\1cloud_AA.las")
#获取文件头
header=las.header
#点类型
point_format=las.point_format
#属性字段名
dimension_name=point_format.dimension_names
#点集外边框
mins=header.mins
maxs=header.maxs
#点个数
point_num=header.point_count
#获取坐标和颜色
las_x=np.array(las.x)
las_y= np.array(las.y)
las_z= np.array(las.z)

las_X=np.array(las.X)
las_Y= np.array(las.Y)
las_Z= np.array(las.Z)

las_r= np.array(las.red)
las_g= np.array(las.green)
las_b= np.array(las.blue)
#堆叠
points=np.stack([las_x,las_y,las_z],axis=1)  #type(points)--->numpy.ndarray
colors=np.stack([las_r,las_g,las_b],axis=1)  #type(colors)--->numpy.ndarray
points_U=np.stack([las_X,las_Y,las_Z],axis=1)
print(points_U[0:2])

print(points[0:2])
print(colors)

[[-49303 193820 -50440]
 [-50399 193718 -50242]]
[[4.64847017e+05 4.39053074e+06 1.24253299e+01]
 [4.64846908e+05 4.39053073e+06 1.24451299e+01]]
[[18176 17664 13824]
 [18176 17920 14848]
 [21504 20736 16640]
 ...
 [34304 34560 33280]
 [25088 22016 19456]
 [17920 17920 17920]]


In [3]:
las.header

<LasHeader(1.2, <PointFormat(2, 0 bytes of extra dims)>)>

In [8]:
las.header.x_offset

464851.9475802512

In [10]:
las.header.y_offset

4390511.359946078

In [11]:
las.header.z_offset

17.469329864210184

In [13]:
las.header.x_scale

0.0001